"""Pull Request title and body builders for the Self-Healing Agent."""


def build_pr_title(lambda_name: str) -> str:
    """Build a concise PR title for an auto-heal fix.

    Args:
        lambda_name: Name of the Lambda function being fixed.

    Returns:
        A Conventional Commits-style title.
    """
    return f"fix: auto-heal {lambda_name}"


def build_pr_description(lambda_name: str, error_summary: str) -> str:
    """Build the Pull Request body with context about the fix.

    Args:
        lambda_name: Name of the affected Lambda function.
        error_summary: Summary or stack trace of the error detected.

    Returns:
        Markdown-formatted PR description.
    """
    return f"""## 🤖 Auto-Heal Pull Request

**Generated by:** Self-Healing Agent (Bedrock AgentCore)
**Affected Lambda:** `{lambda_name}`

### Error Detected

```
{error_summary}
```

### What this PR does

This PR applies a defensive fix to address the error above. Changes include:
- Improved error handling (try-except with specific exceptions)
- Input validation for expected parameters
- Proper logging with `logging.error(..., exc_info=True)`

### Review Checklist

- [ ] The fix addresses the root cause of the error
- [ ] No existing functionality is broken
- [ ] Error handling follows project standards (backend-standards.md)
- [ ] Tests pass after applying this fix

---
> ⚠️ **This PR was generated autonomously.** Human review and approval is mandatory before merging.
"""
